version: '3'

services:
    nginx:
        image: nginx
    
    cloudflared:
        image: judge2020/cloudflare-argo
        environment: 
            - TUNNEL_HOSTNAME=test.judge.sh
            - TUNNEL_URL=http://nginx:80
        volumes:
            - './config:/.cloudflared' # bind mount with cert.pem in it
