name: build
on:
    schedule:
        - cron: '11 4 * * 0'
    push:
        paths:
            - 'Dockerfile'
            - 'login.Dockerfile'
            - '.github/workflows/build.yml'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Login to Docker Repositories
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
              run: |
                docker login -u judge2020 -p $DOCKER_TOKEN
                docker login docker.pkg.github.com -u anything -p $GH_TOKEN
            - run: |
                docker build -t judge2020/cloudflared:latest .
                docker build -t judge2020/cloudflared:login -f login.Dockerfile .
                docker build -t judge2020/cloudflared:argo -f argo.Dockerfile .
            - name: Tag images
              run: |
                docker tag judge2020/cloudflared:latest docker.pkg.github.com/judge2020/docker-cloudflared/cloudflared:$(date +%s)
                docker tag judge2020/cloudflared:latest docker.pkg.github.com/judge2020/docker-cloudflared/cloudflared:latest
                docker tag judge2020/cloudflared:login docker.pkg.github.com/judge2020/docker-cloudflared/cloudflared:login
                docker tag judge2020/cloudflared:argo docker.pkg.github.com/judge2020/docker-cloudflared/cloudflared:argo
                docker tag judge2020/cloudflared:latest judge2020/cloudflared:$(date +%s)
            - name: push
              run: |
                docker push docker.pkg.github.com/judge2020/docker-cloudflared/cloudflared
                docker push judge2020/cloudflared
