name: build
on:
    schedule:
        - cron: '11 4 * * 0'
    push:
        paths:
            - 'Dockerfile'
            - '*.Dockerfile'
            - '.github/workflows/build.yml'

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Login to Docker Repositories
              run: |
                echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
            - run: |
                docker build -t ghcr.io/judge2020/cloudflared:latest . --cache-from ghcr.io/judge2020/cloudflared:latest
                docker build -t ghcr.io/judge2020/cloudflared:login -f login.Dockerfile .
                docker build -t ghcr.io/judge2020/cloudflared:argo -f argo.Dockerfile .
                docker tag ghcr.io/judge2020/cloudflared:latest ghcr.io/judge2020/cloudflared:$(date +%s)
            - name: push
              run: |
                docker push --all-tags ghcr.io/judge2020/cloudflared
